### ISSUE TITLE
Errors when installing the latest version of the package.

### ISSUE THREAD

**Issue by Alvarden15** [nicholas-maltbie/OpenKCC#100]
With the latest version of this package as of this writing (1.0.0), i get errors of dependencies that aren't present in the project:
![lncTqfEffQ](https://user-images.githubusercontent.com/31715989/201942011-94e2f152-bfef-4800-b84d-1010fce4de67.png)

With older versions (0.1.2), this didn't happened. The package worked as expected.

For context, these are the details of the project:
- Unity version used: 2021.3.13f.
- This was a fresh project on URP. I didn't install any additional asset/package beyond the pre installed ones and the ones required by OpenKCC.
- I installed all the required dependencies that are on the ReadMe.
- I used a Scoped Registry to install all of it.
- I didn't download any of the samples at that point.

**Comment by nicholas-maltbie** [comment]
Hi, didn't see this error earlier. This is due to the test assemblies referencing a nuget packet I imported in the project (Moq.dll). 

I'll have to investigate this issue and make sure that this doesn't cause errors when importing or the Moq dll if you want to import the test libraries as well.

**Comment by nicholas-maltbie** [comment]
I opened up PR #101 to address this issue. If you could @Alvarden15 , could you verify that the corrected library imports work on your machine as well?

You can import the test branch from this URL:

```
git+https://github.com/nicholas-maltbie/OpenKCC?path=Packages/com.nickmaltbie.openkcc#nickmaltbie/fix-test-imports
```

**Comment by nicholas-maltbie** [comment]
> So far the test branch installs the package without the errors, although the sample packages don't work with that URL. That been said, it seems to be fixed now.

Yes, the samples are only included when I build the project :D I'll add a short section in the readme and documentation about how to install `Moq.dll` with NuGet for unity then merge the PR. Thanks for the help reviewing the changes!
