### ISSUE TITLE
[Using OpenKCC for AI/Navmesh]

### ISSUE THREAD

**Issue by Bigbossbro08** [nicholas-maltbie/OpenKCC#176]
I want to use OpenKCC for Navmesh/AI. At the same time OpenKCC want to be driven by player as well

I saw several samples just looking around but not sure what exactly to pick up and call it a day. Saw camera getting involved too which is only used by player but not AI. Would be nice if we get a sample keeping both in mind?

**Comment by nicholas-maltbie** [comment]
Hi @Bigbossbro08 sorry I missed this earlier, been moving this month and haven't had as much time to look into this project.

As per the unity documentation on [
NavMesh Agent
Using NavMesh Agent with Other Components](https://docs.unity3d.com/Manual/nav-MixingComponents.html), the best strategy would be to attach a [NavMeshAgent](https://docs.unity3d.com/ScriptReference/AI.NavMeshAgent.html) to the character the make the movement based on [NaveMeshAgent.velocity](https://docs.unity3d.com/ScriptReference/AI.NavMeshAgent-velocity.html)

It's a fairly simple extension and I'm planning on using it in the future. I'll add an example to the project as well as some documentation for NavMeshAgent work with the OpenKCC and call it out this issue in the PR when I have it ready.
