### ISSUE TITLE
Camera Movement Bug

### ISSUE THREAD

**Issue by nicholas-maltbie** [nicholas-maltbie/OpenKCC#234]
> [@tufanaydin6340 ](http://www.youtube.com/channel/UCBZqw4QokrkP2Vg6P0ugnbQ)
> Hey question, i can't change "MinVerticalAngle" and "MaxVerticalAngle" when scene runs it turns default "-90 & +90" how can we change? i can't change.

I wasn't able to repro this bug but logging it for note. I was using the [nickmaltbie.OpenKCC.CameraControls.CameraController](https://nickmaltbie.com/OpenKCC/docs/api/nickmaltbie.OpenKCC.CameraControls.CameraController.html) class

![image](https://github.com/nicholas-maltbie/OpenKCC/assets/3240136/be6e80fd-8553-4b1e-a6ce-08b1a1d6dc71)

**Comment by Tufis16** [comment]
Problem is i can't change max and min vertical angle because in runtime angels are going default. Also in runtime can't change because not updating. 

1- In editor change default camera angles to another different angle for example "-75"
2- Hit play button and look is it changed "probably changed and get back default"
3- Also change in runtime again another different angle "-75" test it in game window it affects from first default floats "-90" 
4- If you want to affect it change in "slider" because code uses "OnValidate()"

**Comment by nicholas-maltbie** [comment]
> Problem is i can't change max and min vertical angle because in runtime angels are going default. Also in runtime can't change because not updating.
> 
> 1 - In editor change default camera angles to another different angle for example "-75"
> 2 - Hit play button and look is it changed "probably changed and get back default"
> 3 - Also change in runtime again another different angle "-75" test it in game window it affects from first default floats "-90"
> 4 - If you want to affect it change in "slider" because code uses "OnValidate()"

Hey @Tufis16, I wasn't able to repro the bug locally on my machine. Could you share a test project where you can re-create the issue and the version of unity and the OpenKCC plugin you are using? I'm currently using the latest master branch of the project and unity version `2023.1.6f1`

Also, as per point 4, the current version of the [CameraController](https://nickmaltbie.com/OpenKCC/docs/api/nickmaltbie.OpenKCC.CameraControls.CameraController.html) does not have an `OnValidate()` method defined. 

The min and max pitch are defined as `minPitch` and `maxPitch` in the [CameraConfig](https://nickmaltbie.com/OpenKCC/docs/api/nickmaltbie.OpenKCC.CameraControls.Config.CameraConfig.html)

**Comment by Tufis16** [comment]
I am really sorry, i realized something, entire time i am looking for this assets bug "Kinematic Character Controller"  not "Open Kinematic Character Controller"

https://assetstore.unity.com/packages/tools/physics/kinematic-character-controller-99131

**Comment by nicholas-maltbie** [comment]
> I am really sorry, i realized something, entire time i am looking for this assets bug "Kinematic Character Controller" not "Open Kinematic Character Controller"
> 
> https://assetstore.unity.com/packages/tools/physics/kinematic-character-controller-99131

No problem, sorry for confusing names. Hope the project and adjustments work out well!
