### ISSUE TITLE
Minor bug with jumping animation v0.0.59

### ISSUE THREAD

**Issue by cjackcandy** [nicholas-maltbie/OpenKCC#51]
Moving animation continues to play (briefly), followed by the idle animation after jump button pressed.

Workaround is to add a transition from Any State to Jumping (in the CharacterAnimationController) with Has Exit Time unchecked and the condition Jumping set to true.

![image](https://user-images.githubusercontent.com/7820933/171007266-1ddf4aa7-f4ff-406d-9757-ad1a3e7812ec.png)
![image](https://user-images.githubusercontent.com/7820933/171007358-8363cc8e-cd9e-4561-bbab-46b6999d2bea.png)

**Comment by nicholas-maltbie** [comment]
Hello, I'll create a small PR to address this issue. 

I think we can also achieve this by explicitly adding a transition from moving/turning. There was a problem where the character wouldn't restart the jump animation if it didn't first move to land, so we don't want jumping to be able to transition from falling or landing. 

There is also a problem where the character will sometimes jitter in place when they turn left or right for similar issues so I will address them in this PR as well :)

**Comment by nicholas-maltbie** [comment]
Hi @cjackcandy, I opened PR #56 to address this issue, the PR description summarizes the changes. 

This should address the error in this character animator. If you see any issues or something I left out in the fix let me know and I will adjust it. I'll probably merge the changes within the next few days if they look good. 

In the near future, I intend to upgrade the entire project to be based as a package and set of samples. As well, I will adjust the character animation to be more dynamic controlled by IK to interact with the local environment. But I will probably keep this around as a simple example for the future 😄
